export const countryCodes = [
    { country: "Afghanistan", code: "AF", dial: "+93" },
    { country: "Albania", code: "AL", dial: "+355" },
    { country: "Algeria", code: "DZ", dial: "+213" },
    { country: "Andorra", code: "AD", dial: "+376" },
    { country: "Angola", code: "AO", dial: "+244" },
    { country: "Argentina", code: "AR", dial: "+54" },
    { country: "Armenia", code: "AM", dial: "+374" },
    { country: "Australia", code: "AU", dial: "+61" },
    { country: "Austria", code: "AT", dial: "+43" },
    { country: "Azerbaijan", code: "AZ", dial: "+994" },
    { country: "Bahrain", code: "BH", dial: "+973" },
    { country: "Bangladesh", code: "BD", dial: "+880" },
    { country: "Belarus", code: "BY", dial: "+375" },
    { country: "Belgium", code: "BE", dial: "+32" },
    { country: "Belize", code: "BZ", dial: "+501" },
    { country: "Benin", code: "BJ", dial: "+229" },
    { country: "Bhutan", code: "BT", dial: "+975" },
    { country: "Bolivia", code: "BO", dial: "+591" },
    { country: "Bosnia and Herzegovina", code: "BA", dial: "+387" },
    { country: "Botswana", code: "BW", dial: "+267" },
    { country: "Brazil", code: "BR", dial: "+55" },
    { country: "Bulgaria", code: "BG", dial: "+359" },
    { country: "Cambodia", code: "KH", dial: "+855" },
    { country: "Cameroon", code: "CM", dial: "+237" },
    { country: "Canada", code: "CA", dial: "+1" },
    { country: "Chile", code: "CL", dial: "+56" },
    { country: "China", code: "CN", dial: "+86" },
    { country: "Colombia", code: "CO", dial: "+57" },
    { country: "Costa Rica", code: "CR", dial: "+506" },
    { country: "Croatia", code: "HR", dial: "+385" },
    { country: "Cuba", code: "CU", dial: "+53" },
    { country: "Cyprus", code: "CY", dial: "+357" },
    { country: "Czech Republic", code: "CZ", dial: "+420" },
    { country: "Denmark", code: "DK", dial: "+45" },
    { country: "Dominican Republic", code: "DO", dial: "+1-809" },
    { country: "Ecuador", code: "EC", dial: "+593" },
    { country: "Egypt", code: "EG", dial: "+20" },
    { country: "El Salvador", code: "SV", dial: "+503" },
    { country: "Estonia", code: "EE", dial: "+372" },
    { country: "Ethiopia", code: "ET", dial: "+251" },
    { country: "Finland", code: "FI", dial: "+358" },
    { country: "France", code: "FR", dial: "+33" },
    { country: "Georgia", code: "GE", dial: "+995" },
    { country: "Germany", code: "DE", dial: "+49" },
    { country: "Ghana", code: "GH", dial: "+233" },
    { country: "Greece", code: "GR", dial: "+30" },
    { country: "Guatemala", code: "GT", dial: "+502" },
    { country: "Honduras", code: "HN", dial: "+504" },
    { country: "Hungary", code: "HU", dial: "+36" },
    { country: "Iceland", code: "IS", dial: "+354" },
    { country: "India", code: "IN", dial: "+91" },
    { country: "Indonesia", code: "ID", dial: "+62" },
    { country: "Iran", code: "IR", dial: "+98" },
    { country: "Iraq", code: "IQ", dial: "+964" },
    { country: "Ireland", code: "IE", dial: "+353" },
    { country: "Israel", code: "IL", dial: "+972" },
    { country: "Italy", code: "IT", dial: "+39" },
    { country: "Jamaica", code: "JM", dial: "+1-876" },
    { country: "Japan", code: "JP", dial: "+81" },
    { country: "Jordan", code: "JO", dial: "+962" },
    { country: "Kazakhstan", code: "KZ", dial: "+7" },
    { country: "Kenya", code: "KE", dial: "+254" },
    { country: "Kuwait", code: "KW", dial: "+965" },
    { country: "Lebanon", code: "LB", dial: "+961" },
    { country: "Libya", code: "LY", dial: "+218" },
    { country: "Malaysia", code: "MY", dial: "+60" },
    { country: "Mexico", code: "MX", dial: "+52" },
    { country: "Morocco", code: "MA", dial: "+212" },
    { country: "Myanmar", code: "MM", dial: "+95" },
    { country: "Nepal", code: "NP", dial: "+977" },
    { country: "Netherlands", code: "NL", dial: "+31" },
    { country: "New Zealand", code: "NZ", dial: "+64" },
    { country: "Nicaragua", code: "NI", dial: "+505" },
    { country: "Nigeria", code: "NG", dial: "+234" },
    { country: "Norway", code: "NO", dial: "+47" },
    { country: "Oman", code: "OM", dial: "+968" },
    { country: "Pakistan", code: "PK", dial: "+92" },
    { country: "Panama", code: "PA", dial: "+507" },
    { country: "Paraguay", code: "PY", dial: "+595" },
    { country: "Peru", code: "PE", dial: "+51" },
    { country: "Philippines", code: "PH", dial: "+63" },
    { country: "Poland", code: "PL", dial: "+48" },
    { country: "Portugal", code: "PT", dial: "+351" },
    { country: "Qatar", code: "QA", dial: "+974" },
    { country: "Romania", code: "RO", dial: "+40" },
    { country: "Russia", code: "RU", dial: "+7" },
    { country: "Saudi Arabia", code: "SA", dial: "+966" },
    { country: "Senegal", code: "SN", dial: "+221" },
    { country: "Serbia", code: "RS", dial: "+381" },
    { country: "Singapore", code: "SG", dial: "+65" },
    { country: "South Africa", code: "ZA", dial: "+27" },
    { country: "South Korea", code: "KR", dial: "+82" },
    { country: "Spain", code: "ES", dial: "+34" },
    { country: "Sri Lanka", code: "LK", dial: "+94" },
    { country: "Sudan", code: "SD", dial: "+249" },
    { country: "Sweden", code: "SE", dial: "+46" },
    { country: "Switzerland", code: "CH", dial: "+41" },
    { country: "Syria", code: "SY", dial: "+963" },
    { country: "Taiwan", code: "TW", dial: "+886" },
    { country: "Tanzania", code: "TZ", dial: "+255" },
    { country: "Thailand", code: "TH", dial: "+66" },
    { country: "Tunisia", code: "TN", dial: "+216" },
    { country: "Turkey", code: "TR", dial: "+90" },
    { country: "Uganda", code: "UG", dial: "+256" },
    { country: "Ukraine", code: "UA", dial: "+380" },
    { country: "United Arab Emirates", code: "AE", dial: "+971" },
    { country: "United Kingdom", code: "GB", dial: "+44" },
    { country: "United States", code: "US", dial: "+1" },
    { country: "Uruguay", code: "UY", dial: "+598" },
    { country: "Venezuela", code: "VE", dial: "+58" },
    { country: "Vietnam", code: "VN", dial: "+84" },
    { country: "Yemen", code: "YE", dial: "+967" },
    { country: "Zambia", code: "ZM", dial: "+260" },
    { country: "Zimbabwe", code: "ZW", dial: "+263" }
];
